export const EventsData = [
  {
    id: 1,
    organizer: 'Organizer',
    website: 'http://localhost:3000/',
    title: 'Title of the event',
    description: 'where these are the same, only the title of the event should be listed',
    logo: 'image.png',
    sideImage: 'image.png',
    city: 'Madrid',
    country: 'Spain',
    month: 'Sep',
    audience: 'IT',
    duration: 'Two days',
    recurrence: 'Annual',
    date: '2020-6-05'
  },
  {
    id: 2,
    organizer: 'Organizer',
    website: 'http://localhost:3000/',
    title: 'Title of the event',
    description: 'where these are the same, only the title of the event should be listed',
    logo: 'image.png',
    sideImage: 'image.png',
    city: 'Madrid',
    country: 'Spain',
    month: 'Sep',
    audience: 'IT',
    duration: 'Two days',
    recurrence: 'Annual',
    date: '2020-7-05'
  },
  {
    id: 3,
    organizer: 'Organizer',
    website: 'http://localhost:3000/',
    title: 'Title of the event',
    description: 'where these are the same, only the title of the event should be listed',
    logo: 'image.png',
    sideImage: 'image.png',
    city: 'Madrid',
    country: 'Spain',
    month: 'Sep',
    audience: 'IT',
    duration: 'Two days',
    recurrence: 'Annual',
    date: '2020-8-05'
  },
  {
    id: 4,
    organizer: 'Organizer',
    website: 'http://localhost:3000/',
    title: 'Title of the event',
    description: 'where these are the same, only the title of the event should be listed',
    logo: 'image.png',
    sideImage: 'image.png',
    city: 'Madrid',
    country: 'Spain',
    month: 'Sep',
    audience: 'IT',
    duration: 'Two days',
    recurrence: 'Annual',
    date: '2020-9-05'
  },
  {
    id: 5,
    organizer: 'Organizer',
    website: 'http://localhost:3000/',
    title: 'Title of the event',
    description: 'where these are the same, only the title of the event should be listed',
    logo: 'image.png',
    sideImage: 'image.png',
    city: 'Madrid',
    country: 'Spain',
    month: 'Sep',
    audience: 'IT',
    duration: 'Two days',
    recurrence: 'Annual',
    date: '2020-10-25'
  },
  {
    id: 6,
    organizer: 'Organizer',
    website: 'http://localhost:3000/',
    title: 'Title of the event',
    description: 'where these are the same, only the title of the event should be listed',
    logo: 'image.png',
    sideImage: 'image.png',
    city: 'Madrid',
    country: 'Spain',
    month: 'Sep',
    audience: 'IT',
    duration: 'Two days',
    recurrence: 'Annual',
    date: '2020-10-15'
  },
  {
    id: 7,
    organizer: 'Organizer',
    website: 'http://localhost:3000/',
    title: 'Title of the event',
    description: 'where these are the same, only the title of the event should be listed',
    logo: 'image.png',
    sideImage: 'image.png',
    city: 'Madrid',
    country: 'Spain',
    month: 'Sep',
    audience: 'IT',
    duration: 'Two days',
    recurrence: 'Annual',
    date: '2020-10-05'
  },

  {
    id: 8,
    organizer: 'Organizer',
    website: 'http://localhost:3000/',
    title: 'Title of the event',
    description: 'where these are the same, only the title of the event should be listed',
    logo: 'image.png',
    sideImage: 'image.png',
    city: 'Madrid',
    country: 'Spain',
    month: 'Sep',
    audience: 'IT',
    duration: 'Two days',
    recurrence: 'Annual',
    date: '2020-11-25'
  },

  {
    id: 9,
    organizer: 'Organizer',
    website: 'http://localhost:3000/',
    title: 'Title of the event',
    description: 'where these are the same, only the title of the event should be listed',
    logo: 'image.png',
    sideImage: 'image.png',
    city: 'Madrid',
    country: 'Spain',
    month: 'Sep',
    audience: 'IT',
    duration: 'Two days',
    recurrence: 'Annual',
    date: '2020-11-15'
  },
  {
    id: 10,
    organizer: 'Organizer',
    website: 'http://localhost:3000/',
    title: 'Title of the event',
    description: 'where these are the same, only the title of the event should be listed',
    logo: 'image.png',
    sideImage: 'image.png',
    city: 'Madrid',
    country: 'Spain',
    month: 'Sep',
    audience: 'IT',
    duration: 'Two days',
    recurrence: 'Annual',
    date: '2020-11-05'
  },

  {
    id: 11,
    organizer: 'Organizer',
    website: 'http://localhost:3000/',
    title: 'Title of the event',
    description: 'where these are the same, only the title of the event should be listed',
    logo: 'image.png',
    sideImage: 'image.png',
    city: 'Madrid',
    country: 'Spain',
    month: 'Sep',
    audience: 'IT',
    duration: 'Two days',
    recurrence: 'Annual',
    date: '2020-12-05'
  },
  {
    id: 12,
    organizer: 'Organizer',
    website: 'http://localhost:3000/',
    title: 'Title of the event',
    description: 'where these are the same, only the title of the event should be listed',
    logo: 'image.png',
    sideImage: 'image.png',
    city: 'Madrid',
    country: 'Spain',
    month: 'Sep',
    audience: 'IT',
    duration: 'Two days',
    recurrence: 'Annual',
    date: '2020-12-15'
  },
  {
    id: 13,
    organizer: 'Organizer',
    website: 'http://localhost:3000/',
    title: 'Title of the event',
    description: 'where these are the same, only the title of the event should be listed',
    logo: 'image.png',
    sideImage: 'image.png',
    city: 'Madrid',
    country: 'Spain',
    month: 'Sep',
    audience: 'IT',
    duration: 'Two days',
    recurrence: 'Annual',
    date: '2020-12-25'
  }
]
